### ISSUE TITLE
Rollen Fertigkeit werden nicht berechnet und haben keinen Effekt auf den wurf

### ISSUE THREAD

**Issue by Licenser** [Gorthian/Roll20_NHKS_CharacterSheet#19]
Rollen Fertigkeit, wenn ausgewählt, berechnen den Endwert nicht korrekt, auch wenn dieser manuell eingetragen wird hat er keinen Einflus auf den Wurf.
 
<img width="582" alt="Screen Shot 2023-10-14 at 01 57 54" src="https://github.com/Gorthian/Roll20_NHKS_CharacterSheet/assets/119093/0037548f-c401-4775-b789-a9fc2318d90c">

**Comment by Licenser** [comment]
Nachtrag: es scheint bei Kampffertigkeiten zu funktionieren

**Comment by Gorthian** [comment]
Fehler behoben und bei Roll20 eingereicht.
Wartet auf Freigabe durch Roll20.

https://github.com/Roll20/roll20-character-sheets/pull/12230

**Comment by Licenser** [comment]
wow :) danke das war schnell!

**Comment by Gorthian** [comment]
Heute wurden die Änderungen auch von Roll20 übernommen.
Eine kurze Rückmeldung ob es jetzt passt, wäre super. ;-)

**Comment by Licenser** [comment]
Gerade getestet 👍 funktioniert einwandfrei danke nochmal!!!
